<?php

namespace Dim\TodoBundle\Repository;

/**
 * StokeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StokeRepository extends \Doctrine\ORM\EntityRepository
{
}
